### ISSUE TITLE
Load error: cannot load such file -- jira

### ISSUE THREAD

**Issue by 2xG** [esigler/lita-jira#23]
`lita-jira-0.8.1/lib/lita-jira.rb:7:in `require': cannot load such file -- jira (LoadError)`

as I see in documentation for jira-ruby it uses no more this Gemfile declaration:
`gem 'jira-ruby', :require => 'jira'`
it uses:
`gem 'jira-ruby', :require => 'jira-ruby'`
instead.

**Comment by esigler** [comment]
Thanks for the report!  Fixed in master now, will cut a release soon!
