### ISSUE TITLE
When issue is unassigned, "jira details issueKey" causes a crash.

### ISSUE THREAD

**Issue by JessicaSachs** [esigler/lita-jira#5]
Test Case:

1. Create an issue as unassigned
2. Ask lita to fetch its summary via `jira issueKey`

Observe: works fine. Returns issue summary

3. Ask lita to fetch its details via `jira details issueKey`

Observe: Nothing returns in the chat, crash logs seen in lita's logs

	[2015-02-26 18:01:31 UTC] ERROR: Lita::Handlers::Jira crashed. The exception was:
	undefined method `displayName' for nil:NilClass
	Full backtrace:
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-jira-0.5.0/lib/jirahelper/issue.rb:23:in `format_issue'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-jira-0.5.0/lib/lita/handlers/jira.rb:63:in `details'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/callback.rb:31:in `public_send'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/callback.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/handler/chat_router.rb:88:in `dispatch_to_route'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/handler/chat_router.rb:73:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/handler/chat_router.rb:70:in `map'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/handler/chat_router.rb:70:in `dispatch'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/robot.rb:58:in `block in receive'
	/usr/local/lib/ruby/2.1.0/set.rb:263:in `each_key'
	/usr/local/lib/ruby/2.1.0/set.rb:263:in `each'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/robot.rb:55:in `map'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/robot.rb:55:in `receive'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack/message_handler.rb:50:in `dispatch_message'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack/message_handler.rb:85:in `handle_message'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack/message_handler.rb:17:in `handle'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack/rtm_connection.rb:97:in `receive_message'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack/rtm_connection.rb:46:in `block (2 levels) in run'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:31:in `block in emit'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:30:in `each'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:30:in `emit'
	/usr/local/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/usr/local/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:95:in `receive_message'
	/usr/local/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:38:in `block in initialize'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:31:in `block in emit'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:30:in `each'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/event_emitter.rb:30:in `emit'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/hybi.rb:397:in `emit_message'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/hybi.rb:380:in `emit_frame'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/hybi.rb:118:in `parse'
	/usr/local/lib/ruby/gems/2.1.0/gems/websocket-driver-0.5.3/lib/websocket/driver/client.rb:57:in `parse'
	/usr/local/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:134:in `parse'
	/usr/local/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/client.rb:77:in `receive_data'
	/usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack/rtm_connection.rb:37:in `run'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-slack-1.1.0/lib/lita/adapters/slack.rb:15:in `run'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/robot.rb:69:in `run'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita.rb:79:in `run'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/lib/lita/cli.rb:77:in `start'
	/usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/usr/local/lib/ruby/gems/2.1.0/gems/lita-4.2.0/bin/lita:6:in `<top (required)>'
	/usr/local/bin/lita:23:in `load'
	/usr/local/bin/lita:23:in `<main>'

**Comment by esigler** [comment]
Thanks for the bug report & repo steps!  I'll look into this shortly.

**Comment by xenjke** [comment]
Confirming the same steps to reproduce.

**Comment by esigler** [comment]
Fixed in PR #6, will cut a new release version shortly.
